spring.application.name=listme
server.port=8089
spring.datasource.url=${LISTME_DB_URL:jdbc:postgresql://localhost:5433/list_me}
spring.datasource.username=${LISTME_DB_USERNAME:admin}
spring.datasource.password=${LISTME_DB_PASSWORD:angelc45}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${LISTME_JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false

# Security Configuration (JWT)
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=2592000000
